name: MineDisaster
version: 1.0.0
main: com.kakamine.minedisaster.MineDisaster
api-version: 1.21
author: kakamine
commands:
  disaster:
    description: MineDisaster 제어 명령어
    usage: /disaster
permissions:
  minedisaster.*:
    default: op
    children:
      minedisaster.meteor: true
      minedisaster.bacteria: true
      minedisaster.doomsday: true
      minedisaster.earthquake: true
      minedisaster.reload: true
